---
# tasks file for monitoring

- name: Unpacking nagios-plugins zip file into temp
  unarchive:
   src: nagios-plugins-2.3.3.tar.gz
   dest: /tmp
   
- name: Configuring, making and install the above
  shell: cd /tmp/nagios-plugins-2.3.3 && ./configure && make && make install 
 
- name: Deploying monitoring nagios config file
  copy:
   src: shark_monitoring.cfg
   dest: /usr/local/nagios/etc/conf.d/
  notify: restart-nagios
