---
# tasks file for httpd
- name: Install apache2 
  apt:
   name: apache2

- name: Installing php deps
  apt:
   name: "{{ item }}"
  with_items: 
   - php
   - libapache2-mod-php

- name: Starting apache
  service:
   name: apache2 
   state: started
