---

- name: Automated Platform Trading Role
  hosts: atp-server
  become: true
  vars:
          webui_auth_user: nagios
          webui_auth_pass: nagios

          
  roles:
  - server-prep
  - httpd
  - nagios-from-source
  - automatedtradingplatform
 
- name: Running nagios self santize to detect errors
  become: true
  shell: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
