---

- name: Automated Platform Trading Role
  hosts: atp-server
  become: true
  vars:
          webui_auth_user: nagios
          webui_auth_pass: nagios

          set_strategy: "moving_averages.py"
  roles:
  - server-prep
  - httpd
  - base-from-source
  - automatedtradingplatform
