---
# tasks file for nagios-from-source

- name: Including build essentials
  include: build_essentials.yml

- name: Adding nagios group
  group:
    name: nagios
    state: present

- name: Adding nagios user
  user:
    name: nagios
    group: nagios

- name: Creating nagios directories
  file:
    path: /usr/local/nagios
    owner: nagios
    group: nagios
    state: directory

- name: Creating nagios directories
  file:
    path: /usr/local/nagios/bin
    owner: nagios
    group: nagios
    state: directory

- name: Unpacking zip file into temp
  unarchive:
   src: nagios-4.4.6.tar.gz
   dest: /tmp

- name: Building nagios from source
  shell: cd /tmp/nagios-4.4.6 && ./configure && make all && make install && make install-daemoninit && make install-commandmode && make install-config && make install-webconf
