# This is how you apply each check to specifics ticker.

# The structure of this file is important (as in indentation being yaml).

# <ticker>:
#
# <check_unique_name>
#  description: "<Check description - what appears in the web UI>"
#  check_command: <check_command>
#  <check_argument>: <arg>
#  <check_argument>: <arg>
#  <check_argument>: <arg>

AMC:

 RSI Check: 
  description: "RSI [ 14 Day ]"
  check_command: check_rsi
  ticker: AMC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Stategy: Moving Averages"
  check_command: check_strategy
  ticker: AMC
  name: moving_averages.py
   
 Backtest:
  description: "Backtest: Moving Averages"
  check_command: check_backtest
  ticker: ANZ
  name: backtest_moving_averages.py
  shares: 1000
  capital: 100000
 
ANZ:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: ANZ
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: ANZ
  name: moving_averages.py
  
BHP:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: BHP
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: BHP
  name: moving_averages.py

BXB:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: BXB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: BXB
  name: moving_averages.py

CBA:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: CBA
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: CBA
  name: moving_averages.py

CSL:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: CSL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: CSL
  name: moving_averages.py

GMG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: GMG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: GMG
  name: moving_averages.py
   
IAG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: IAG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: IAG
  name: moving_averages.py
 
MQG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: MQG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: MQG
  name: moving_averages.py

NAB:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: NAB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: NAB
  name: moving_averages.py
   
NCM:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: NCM
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: NCM
  name: moving_averages.py

RIO:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: RIO
  period: 14
  min: 10
  max: 90

  Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: RIO
  name: moving_averages.py
  
SCG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: SCG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: SCG
  name: moving_averages.py

SUN:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: SUN
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: SUN
  name: moving_averages.py

TLS:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: TLS
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: TLS
  name: moving_averages.py

TCL:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: TCL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: TCL
  name: moving_averages.py
   
WES:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WES
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: WES
  name: moving_averages.py

WBC:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WBC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: WBC
  name: moving_averages.py
  
WPL:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WPL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: WPL
  name: moving_averages.py
  
WOW:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WOW
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 50 Days:
  description: "SIMPLE MOVING AVERAGE: [ 50 Day ]"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "SIMPLE MOVING AVERAGE: [ 5 Day ]"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy
  ticker: WOW
  name: moving_averages.py
