# This is how you apply each check to specifics ticker.

# The structure of this file is important (as in indentation being yaml).

# <ticker>:
#
# <check_unique_name>
#  description: "<Check description - what appears in the web UI>"
#  check_command: <check_command>
#  <check_argument>: <arg>
#  <check_argument>: <arg>
#  <check_argument>: <arg>

AMC:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: AMC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

ANZ:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: ANZ
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
BHP:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: BHP
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

BXB:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: BXB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

CBA:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: CBA
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

CSL:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: CSL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

GMG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: GMG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
IAG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: IAG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
 
MQG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: MQG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

NAB:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: NAB
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
NCM:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: NCM
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

RIO:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: RIO
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
SCG:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: SCG
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

SUN:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: SUN
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

TLS:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: TLS
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

TCL:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: TCL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
WES:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WES
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

WBC:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WBC
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
WPL:

 Check RSI2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WPL
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
WOW:

 RSI Check: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  ticker: WOW
  period: 14
  min: 10
  max: 90

 Simple Moving Average - 10 Days:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 Simple Moving Average - 5 Days:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 Strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
