# This is how you apply each check to specifics ticker.

# The structure of this file is important (as in indentation being yaml).

# <ticker>:
#
# <check_unique_name>
#  description: "<Check description - what appears in the web UI>"
#  check_command: <check_command>
#  <check_argument>: <arg>
#  <check_argument>: <arg>
#  <check_argument>: <arg>

AMC:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

ANZ:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
BHP:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

BXB:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

CBA:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

CSL:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

GMG:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
IAG:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
 
MQG:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

NAB:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
NCM:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

RIO:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
SCG:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

SUN:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

TLS:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

TCL:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
   
WES:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages

WBC:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
WPL:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
  
WOW:

 check_rsi2: 
  description: "RSI 14 Day - Warn if either side of 10 or 90"
  check_command: check_rsi
  period: 14
  min: 10
  max: 90

 check_sma50:
  description: "Moving Average 50 Day"
  check_command: check_sma 
  period: 50

 check_sma5:
  description: "Moving Average 5 Day"
  check_command: check_sma 
  period: 5

 strategy: 
  description: "Moving Averages Strategy v.01"
  check_command: check_strategy 
  name: moving_averages
