---
# tasks file for apache-drill

- name: Install java (required for Apache Drill )
  apt:
   name: default-jre
   state: latest
   
- name: Downloading apache drill (This is a crap way to do it, but ansible's get_url kept redownload the file slowing everything down)
  shell: cd /shark && wget -N http://apache.mirrors.hoobly.com/drill/drill-1.18.0/apache-drill-1.18.0.tar.gz

- name: Unzipping the above
  unarchive: 
   src: /shark/apache-drill-1.18.0.tar.gz
   dest: /shark/

- name: Install setup tools for python3
  pip:
   name: setuptools
   executable: pip3

- name: Install JayDeBeApi which is prereq for python and jdbc connectivitty
  pip:
   name: JayDeBeApi
   executable: pip3

- name: Installing pandas
  pip:
   name: pandas
   executable: pip3

- name: Copying configuration file
  copy:
   src: drill-override.conf
   dest: /shark/apache-drill-1.18.0/conf/
   
- name: Ensure group "drill" exists
  group:
    name: drill
    state: present
    
- name: Add drill user
  user:
    name: drill
    shell: /bin/bash
    groups: drill 
    
- name: Configuring permissions on the above
  file: 
   dest: /shark/apache-drill-1.18.0
   owner: drill 
   group: drill 
   recurse: yes
   
- name: Adding drill systemd file
  copy:
   src: drill.service
   dest: /etc/systemd/system/

- name: Starting drill
  service:
   name: drill
   state: started
   enabled: true
