---
# tasks file for apache-drill

- name: Install java (required for Apache Drill )
  apt:
   name: default-jre
   state: latest
   
- name: Creating Apache Drill work directory
  file:
    path: /shark/apache-drill
    state: directory
    mode: 0755

- name: Downloading apache drill (This is a crap way to do it, but ansible's get_url kept redownload the file slowing everything down)
  shell: cd /shark/apache-drill && wget -N http://apache.mirrors.hoobly.com/drill/drill-1.18.0/apache-drill-1.18.0.tar.gz

- name: Unzipping the above
  unarchive: 
   src: /shark/apache-drill/apache-drill-1.18.0.tar.gz
   dest: /shark/apache-drill/

- name: Install JayDeBeApi which is prereq for python and jdbc connectivitty
  pip:
   name: JayDeBeApi
   executable: pip3

- name: Installing pandas
  pip:
   name: pandas
   executable: pip3

- name: Configuring our necessary system environment variables /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"

