---
# tasks file for apache-drill

- name: Install java (required for Apache Drill )
  apt:
   name: default-jre
   state: latest
   
- name: Creating Apache Drill work directory
  file:
    path: /shark/apache-drill
    state: directory
    mode: 0755
   
- name: Downloading apache drill
  get_url:
    url: http://apache.mirrors.hoobly.com/drill/drill-1.18.0/apache-drill-1.18.0.tar.gz
    dest: /shark/apache-drill
    mode: 0755
    
