---
# tasks file for automatedtradingplatform

- name: Creating back testing working directory
  file:
    name: /atp/backtesting
    owner: atp
    group: atp
    state: directory

- name: Copy our ASX List of companies downloaded from the ASX site. 
  unarchive:
    src: PyAlgoTrade-0.18.tar.gz
    dest: /atp/backtesting
    owner: atp
    group: atp

- name: Deps for the above
  apt:
   name: python3-setuptools
   state: latest
