---
# tasks file for automatedtradingplatform

- name: Adding atp group
  group:
    name: atp
    state: present

- name: Adding atp user
  user:
    name: atp
    comment: AutomatedTradingPlatform user account
    group: atp
    shell: /bin/false
    home: /atp

- name: Creating atp working directory
  file:
    name: /atp
    owner: atp
    group: atp
    state: directory

- name: Creating ticker data dir
  file:
   name: /atp/tickerdata
   owner: atp
   group: atp
   state: directory

- name: Copy our ASX List of companies downloaded from the ASX site. 
  copy:
    src: ASX_Listed_Companies.csv
    dest: /atp/
    owner: atp
    group: atp

- name: Copying out list of excluded tickers
  copy: 
   src: excluded_tickers.txt
   dest: /atp/

- name: Copying in our nagios ticker config generation script
  copy:
   src: process_tickers.py
   dest: /atp
   owner: atp
   group: atp

- name: Copying in custom UI changes - side.php
  copy:
   src: ui_patches/side.php
   dest: /tmp/nagios-4.4.6/html

- name: Copying in custom UI changes - status.c
  copy:
   src: ui_patches/status.c
   dest: /tmp/nagios-4.4.6/cgi
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/extinfo.c
   dest: /tmp/nagios-4.4.6/cgi
  notify:
  - rebuild-nagios
  - restart-nagios

- meta: flush_handlers

- include: nagios_configuration.yml
