---
# tasks file for automatedtradingplatform

- name: Adding atp group
  group:
    name: atp
    state: present

- name: Adding atp user
  user:
    name: atp
    comment: AutomatedTradingPlatform user account
    group: atp
    shell: /bin/false
    home: /atp

- name: Creating atp working directory
  file:
    name: /atp
    owner: atp
    group: atp
    state: directory

- name: Creating tmp cache directory
  file:
   name: /tmp/.atp
   group: atp
   owner: atp
   state: directory

- name: Creating websites cache directory
  file:
   name: /tmp/.atp/websites
   group: atp
   owner: atp
   state: directory

- name: Synchronsing ticker data dir
  copy: 
   src: ticker-data
   dest: /atp/
   owner: atp
   group: atp

- name: Copy our ASX List of companies downloaded from the ASX site. 
  copy:
    src: ASX_Listed_Companies.csv
    dest: /atp/
    owner: atp
    group: atp

- name: Copying out list of excluded tickers
  copy: 
   src: excluded_tickers.txt
   dest: /atp/

- name: Copying in our nagios ticker config generation script
  copy:
   src: process_tickers.py
   dest: /atp
   owner: atp
   group: atp

- name: Copying in custom UI changes - side.php
  copy:
   src: ui_patches/side.php
   dest: /tmp/nagios-4.4.6/html

- name: Copying in custom UI changes - status.c
  copy:
   src: ui_patches/status.c
   dest: /tmp/nagios-4.4.6/cgi
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/extinfo.c
   dest: /tmp/nagios-4.4.6/cgi
  notify:
  - rebuild-nagios
  - restart-nagios

- meta: flush_handlers

- include: nagios_configuration.yml

- include: back_testing.yml

- include: website_check.yml

- include: check_rsi.yml

- include: check_short.yml

- name: Running nagios self santize to detect errors
  shell: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
  register: shell_result

- debug: 
        var: shell_result.stdout_lines
