---
# tasks file for automatedtradingplatform

- name: Install pip
  apt:
   name: python3-pip
   state: latest

- name: Install Python Requests
  apt:
   name: python3-requests
   state: latest

- name: Installing wkhtmltoimage in order to be able to screenshot images
  apt:
   name: wkhtmltopdf
   state: latest

- name: Install httpd (should be already installed but just to show its a dep) for testing the check_website plugins
  apt:
   name: apache2
   state: latest

- name: Starting httpd save as above
  service:
   name: apache2
   state: started

- name: Test web file multiple changing lines
  copy:
   src: web_tests/changing-page-multiple-lines.php
   dest: /var/www/html
   mode: 0755
   owner: root
   group: root

- name: Test web file unchanging
  copy:
   src: web_tests/unchanging-page.php
   dest: /var/www/html
   mode: 0755
   owner: root
   group: root

- name: Test web file single line changing
  copy:
   src: web_tests/changing-page-single-line.php
   dest: /var/www/html
   mode: 0755
   owner: root
   group: root

- name: Adding websites to monitor
  template: 
    src: website-check-template.cfg
    dest: /usr/local/nagios/etc/conf.d/{{ item.filename }}
  with_items:  
    - { 
        filename: cba.cfg,
        ticker: CBA, 
        desc: "Investors Centre Website", 
        url: "https://www.commbank.com.au/about-us/investors/asx-announcements.html",
        checksum: ""
      }
    - { 
        filename: tls.cfg,
        ticker: TLS, 
        desc: "Investors Centre Website", 
        url: "https://www.telstra.com.au/aboutus/investors",
        checksum: ""
      }
  notify: restart-nagios
