---
# tasks file for server-prep
- name: Setting system timezone.
  timezone:
   name: "{{ timezone }}"

- name: Updating System
  apt: 
   update_cache: yes

- name: Installing rsync
  apt:
   name: rsync
   state: latest

- name: Install curl
  apt:
   name: curl
   state: latest
