---
# tasks file for server-prep
- name: Setting timezone to AEST to match the ASX opening hours.
  timezone:
   name: Australia/Sydney

- name: Updating System
  apt: 
   update_cache: yes

- name: Installing rsync
  apt:
   name: rsync
   state: latest